name: Log in to Quay.io

on:
  push:
env:
  REGISTRY_USER: lam_quay
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  login:


    

    name: Log in to image registry
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}
      - name : list containers
        run  : docker ps
      - name : list container images
        run  :  docker images 
      - name : build image
        run  : docker build -t tackle-container-advisor ./Dockerfile 
      - name : push to quay
        run  : docker push  tackle-container-advisor
    