name: Create and Publish a TCA release

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: push_to_quay
      - name: Get release tag
        id: get_release_tag
        run: echo ::set-output name=tag_name::${GITHUB_REF#refs/tags/}
      - name: Build Changelog
        id: gen_changelog
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          failOnError: "true"
          configuration: .github/workflows/release_config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.gen_changelog.outputs.changelog }}

  publish-release:
      needs: tagged-release
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
           ref: push_to_quay
        - name : get tag
          run:  echo ${{needs.tagged-release.get_release_tag}}
        - name: Log in to Quay.io
          uses: redhat-actions/podman-login@v1
          with:
            username: ${{ env.REGISTRY_USER }}
            password: ${{ env.REGISTRY_PASSWORD }}
            registry: ${{ env.IMAGE_REGISTRY }}
        - name : build image
          run  : docker build -t tca .
        - name : tag image
          run  : docker tag tca:latest  quay.io/konveyor/tackle-container-advisor:${{needs.tagged-release.get_release_tag}}
        - name : push to quay
          run  : docker push quay.io/konveyor/tackle-container-advisor:latest


    

