name: Unit test cases for TCA
on: [push,pull_request]
jobs:
  run-unit-tests:
    name: Run unit test cases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cleanup
        run: |
          bash clean.sh
      - name: Setup Containerization Advisor
        run: |
          bash setup.sh
      - name: Test with pytest
        id: run-unit-tests
        run: |
          python -m unittest discover -v -s test -p test_*.py
  
  build:
    needs: run-unit-tests
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: my-app
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    # Podman Login action (https://github.com/redhat-actions/podman-login) also be used to log in,
    # in which case 'username' and 'password' can be omitted.
    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/lam_quay
        username: lam_quay
        password: ${{ secrets.REGISTRY_PASSWORD }}