name: Unit tests
on: [push,pull_request]

jobs:
  run-unit-tests:
    name:  tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cleanup
        run: |
          bash clean.sh
      - name: Setup Containerization Advisor
        run: |
          bash setup.sh
      - name: Test with pytest
        id: run-tests
        run: |
          python -m unittest discover -v -s test -p test_*.py
      